#  Numpy

In [1]:
import numpy as np 

In [2]:
myarr = np.array([[3,6,37,7]], np.int64)

In [3]:
myarr[0, 1]

6

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]= 45

In [7]:
myarr

array([[ 3, 45, 37,  7]], dtype=int64)

#  Arry creation: conversion from other Python structures

In [8]:
listarray = np.array ([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
rng = np.arange(15)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
lspace = np.linspace(1,50,10) # 10 = elements

In [19]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        7.56602523e-307, 4.45057212e-308, 1.06811422e-306],
       [7.56587584e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.60220393e-306, 6.89805151e-307, 1.78020169e-306],
       [8.45559303e-307, 8.06613465e-308, 6.89810244e-307,
        1.22387550e-307, 2.22522596e-306, 4.94065646e-322]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
ide = np.identity(45)

In [25]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [26]:
ide.shape

(45, 45)

In [27]:
arr = np.arange(99)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr.reshape(3,33) #it gives 3,33 matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.shape

(99,)

In [32]:
x = [[1,2,3],[4,5,6],[7,8,0]]

In [33]:
ar = np.array(x)

In [34]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [35]:
ar.sum(axis = 0)

array([12, 15,  9])

In [36]:
ar.sum(axis=1)

array([ 6, 15, 15])

In [37]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 0]])

In [38]:
ar.flat

In [39]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
0


In [40]:
ar.ndim

2

In [41]:
ar.size

9

In [42]:
ar.nbytes

36

In [43]:
one = np.array([1,3,4,634,2])

In [44]:
one.argmax() # it find index of highest value in array

3

In [45]:
one.argmin()

0

In [46]:
one.argsort() # it shows index after sort elements in asending order 

array([0, 4, 1, 2, 3], dtype=int64)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [48]:
ar.argmin()

8

In [49]:
ar.argmax()

7

In [50]:
ar.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [51]:
ar.argmin(axis=0)

array([0, 0, 2], dtype=int64)

In [52]:
ar.argsort(axis =1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [53]:
ar.argsort(axis = 0)

array([[0, 0, 2],
       [1, 1, 0],
       [2, 2, 1]], dtype=int64)

In [54]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 0])

In [55]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [0]])

In [56]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [57]:
ar2 = np.array([[1,2,1],
               [4,0,6],
               [8,1,0]])

In [58]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [59]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  9,  0]])

In [60]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  8,  0]])

In [61]:
ar2%ar

C:\Users\PRAMOD~1\AppData\Local\Temp/ipykernel_1284/1459942709.py:1: RuntimeWarning: divide by zero encountered in remainder
  ar2%ar


array([[0, 0, 1],
       [0, 0, 0],
       [1, 1, 0]], dtype=int32)

In [62]:
ar2/ar

C:\Users\PRAMOD~1\AppData\Local\Temp/ipykernel_1284/3416719587.py:1: RuntimeWarning: invalid value encountered in true_divide
  ar2/ar


array([[1.        , 1.        , 0.33333333],
       [1.        , 0.        , 1.        ],
       [1.14285714, 0.125     ,        nan]])

In [63]:
ar2-ar

array([[ 0,  0, -2],
       [ 0, -5,  0],
       [ 1, -7,  0]])

In [64]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.        ],
       [2.        , 0.        , 2.44948974],
       [2.82842712, 1.        , 0.        ]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 0.        ]])

In [66]:
ar.sum()

36

In [67]:
ar.max()

8

In [68]:
ar.min()

0

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [70]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [71]:
np.where(ar<5)

(array([0, 0, 0, 1, 2], dtype=int64), array([0, 1, 2, 0, 2], dtype=int64))

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [73]:
np.count_nonzero(ar)

8