## <center><font color = green><font size =6> Data Cleaning and Preparation

# 1.  Handling misssing data

**sentinel value ->** For numeric data, pandas uses the floating-point value NaN (Not a Number) to represent missing data.

 **Find missing values in data**
 
1. df.isnull()

2. df.notnull()

**NA handling method**

**dropna :-**  Filter axis labels based on whether values for each label have missing data, with varying thresholds for how much missing data to tolerate.

**fillna :-**  Fill in missing data with some value or using an interpolation method such as 'ffill' or 'bfill'.

**isnull :-**  Return boolean values indicating which values are missing/NA.

**notnull :-**  Negation of isnull.

In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA

In [2]:
data = pd.DataFrame([[1., 6.5, 3.,1.0], [1., NA, NA,NA],
                    [NA, 3.5, NA,NA], [NA, 6.5, 3.,5.6]])

In [3]:
data

0    1    2    3
0  1.0  6.5  3.0  1.0
1  1.0  NaN  NaN  NaN
2  NaN  3.5  NaN  NaN
3  NaN  6.5  3.0  5.6

In [4]:
print(data.isnull(),"\n")
print(data.isnull().sum())

       0      1      2      3
0  False  False  False  False
1  False   True   True   True
2   True  False   True   True
3   True  False  False  False 

0    2
1    1
2    2
3    2
dtype: int64


In [5]:
print(data.notnull(),"\n")
print(data.notnull().sum())

       0      1      2      3
0   True   True   True   True
1   True  False  False  False
2  False   True  False  False
3  False   True   True   True 

0    2
1    3
2    2
3    2
dtype: int64


In [6]:
cleaned = data.dropna() 

# data.dropna(how="all") ---> Passing how='all' will only drop rows that are all NA

In [7]:
cleaned

0    1    2    3
0  1.0  6.5  3.0  1.0

In [8]:
data[4] = NA
data

0    1    2    3   4
0  1.0  6.5  3.0  1.0 NaN
1  1.0  NaN  NaN  NaN NaN
2  NaN  3.5  NaN  NaN NaN
3  NaN  6.5  3.0  5.6 NaN

In [9]:
data.dropna(axis=1, how="all") # To drop columns in the same way, pass axis=1:

0    1    2    3
0  1.0  6.5  3.0  1.0
1  1.0  NaN  NaN  NaN
2  NaN  3.5  NaN  NaN
3  NaN  6.5  3.0  5.6

In [10]:
data

0    1    2    3   4
0  1.0  6.5  3.0  1.0 NaN
1  1.0  NaN  NaN  NaN NaN
2  NaN  3.5  NaN  NaN NaN
3  NaN  6.5  3.0  5.6 NaN

# Filling missing value

In [11]:
data

0    1    2    3   4
0  1.0  6.5  3.0  1.0 NaN
1  1.0  NaN  NaN  NaN NaN
2  NaN  3.5  NaN  NaN NaN
3  NaN  6.5  3.0  5.6 NaN

In [12]:
data1 = data.fillna(0)
data1

0    1    2    3    4
0  1.0  6.5  3.0  1.0  0.0
1  1.0  0.0  0.0  0.0  0.0
2  0.0  3.5  0.0  0.0  0.0
3  0.0  6.5  3.0  5.6  0.0

In [13]:
data2 = data.fillna({0:1,1:2,2:3,3:4,4:"go"})  
# Calling fillna with a dict, you can use a different fill value for each column
data2

0    1    2    3   4
0  1.0  6.5  3.0  1.0  go
1  1.0  2.0  3.0  4.0  go
2  1.0  3.5  3.0  4.0  go
3  1.0  6.5  3.0  5.6  go

In [14]:
# With fillna you can do lots of other things with a little creativity. 
# For example, you might pass the mean or median value of a Series.

data3= data.fillna(data.mean())
data3

0    1    2    3   4
0  1.0  6.5  3.0  1.0 NaN
1  1.0  5.5  3.0  3.3 NaN
2  1.0  3.5  3.0  3.3 NaN
3  1.0  6.5  3.0  5.6 NaN

# <center>Data Transformation

## 1.  Removing duplicates

Duplicate rows may be found in a DataFrame for any number of reasons.

In [15]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                    'k2': [1, 1, 2, 3, 3, 4, 4]})

In [16]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [17]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [18]:
data1 = data.drop_duplicates()
data1

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [19]:
data["v1"] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [20]:
data2 = data.drop_duplicates(["k1"]) # by defalut delete second duplicate value
data2

k1  k2  v1
0  one   1   0
1  two   1   1

In [21]:
data3 = data.drop_duplicates(["k2"],keep="last") # it will delete first duplicate value
data3

k1  k2  v1
1  two   1   1
2  one   2   2
4  one   3   4
6  two   4   6

## 2. Replacing Values

In [22]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [23]:
data1 = data.replace(-999, np.nan)
data1

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [24]:
data2 = data.replace([-999,-1000], np.nan) # multiple value at ones
data2

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [25]:
data3 = data.replace({-999: np.nan, -1000: 0}) # argument passed can also be a dict
data3

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## 3. Renaming Axis Indexes

In [26]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [27]:
data1 = data.rename(index=str.title, columns=str.upper)
data1

ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [28]:
data2 = data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})
data2

one  two  peekaboo  four
Ohio        0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

## 4. String Manipulation

In [29]:
val = "a, b, guido"
val

'a, b, guido'

In [30]:
data1 = val.split(',')
data1

['a', ' b', ' guido']

In [31]:
data2 = val.replace(',',"::")
data2

'a:: b:: guido'

In [32]:
val.count(',')

2

## <center><font color = green><font size =6> Data Wrangling: join, combine and Reshape

## 1. Hierarchical Indexing

1. Hierarchical indexing is an important feature of pandas that enables you to have multiple (two or more) index levels on an axis. Somewhat abstractly, it provides a way for you to work with higher dimensional data in a lower dimensional form.


2. Hierarchical indexing plays an important role in reshaping data and group-based operations like forming a pivot table. For example, you could rearrange the data into a DataFrame using its unstack method:

In [33]:
data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1   -0.316634
   2   -0.756015
   3    0.404491
b  1   -1.090997
   3    0.045267
c  1   -0.688275
   2    0.051385
d  2   -0.890338
   3    1.518219
dtype: float64

In [34]:
data1= data.unstack()
data1

1         2         3
a -0.316634 -0.756015  0.404491
b -1.090997       NaN  0.045267
c -0.688275  0.051385       NaN
d       NaN -0.890338  1.518219

In [35]:
data1.stack() # inverse of unstack()

a  1   -0.316634
   2   -0.756015
   3    0.404491
b  1   -1.090997
   3    0.045267
c  1   -0.688275
   2    0.051385
d  2   -0.890338
   3    1.518219
dtype: float64

## 2. Combining and Merging Datasets

**Data contained in pandas objects can be combined together in a number of ways:**

- **pandas.merge** connects rows in DataFrames based on one or more keys. This will be familiar to users of SQL or other relational databases, as it implements database join operations.


- **pandas.concat** concatenates or “stacks” together objects along an axis.


- The ***combine_first*** instance method enables splicing together overlapping data to fill in missing values in one object with values from another.

In [36]:
# pd.merge(df1, df2, on ="column_name")

#### Different join types with how argument

**'inner':-**   Use only the key combinations observed in both tables


**'left':-**   Use all key combinations found in the left table


**'right':-**   Use all key combinations found in the right table


**'output':-**   Use all key combinations observed in both tables together



## Concatenating Along an Axis

In [37]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
np.concatenate([arr, arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
np.concatenate([arr, arr], axis= 1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [40]:
s1 = pd.Series([0,1],index=("a","b"))
s2 = pd.Series([2,3,4], index=('c','d','e'))
s3 = pd.Series([5,6], index= ('f','g'))

In [41]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [42]:
pd.concat([s1,s2,s3], axis=1)

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [43]:
pd.concat([s1, s1, s3], keys=['one', 'two', 'three'])

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [44]:
s4 = pd.concat([s1,s2])
s4

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [45]:
pd.concat([s1,s4], axis=1)

0  1
a  0.0  0
b  1.0  1
c  NaN  2
d  NaN  3
e  NaN  4

In [46]:
pd.concat([s1,s4], axis=1, join='inner') # only common part of both table

0  1
a  0  0
b  1  1

In [47]:
# pd.concat([s1, s4], axis=1, join_axes=[['a', 'c', 'b', 'e']])

## 3.Reshaping and Pivoting

There are a number of basic operations for rearranging tabular data. These are alter‐
natingly referred to as reshape or pivot operations.

## Reshaping

**stack :-** This “rotates” or pivots from the columns in the data to the rows.

**unstack :-** This pivots from the rows into the columns.

In [48]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(['Ohio', 'Colorado'], name='state'),
                    columns=pd.Index(['one', 'two', 'three'],
                    name='number'))
data

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

In [49]:
reshape = data.stack()
reshape

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int32

In [50]:
unshape = reshape.unstack()
unshape

number    one  two  three
state                    
Ohio        0    1      2
Colorado    3    4      5

## Pivoting “Long” to “Wide” Format

A common way to store multiple time series in databases and CSV is in so-called long
or stacked format. 

In [51]:
df = pd.DataFrame({'key': ['foo', 'bar', 'baz'],
                 'A': [1, 2, 3],
                 'B': [4, 5, 6],
                 'C': [7, 8, 9]})
df

key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

**An inverse operation to pivot for DataFrames is *pandas.melt*.**

In [52]:
melted = pd.melt(df,["key"])
melted

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

In [53]:
reshaped = melted.pivot('key', 'variable', 'value')
reshaped

variable  A  B  C
key              
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [54]:
pd.melt(df, id_vars=['key'], value_vars=['A', 'B']) 
# You can also specify a subset of columns to use as value columns

key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6